# Generated by Django 4.2.1 on 2023-05-20 09:05

from django.db import migrations, models
import django.db.models.deletion
import ndam.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('port', models.IntegerField(default=22)),
                ('connection_type', models.IntegerField(choices=[(0, 'SSH')], default=0)),
                ('modul_type', models.IntegerField(choices=[(0, 'Mikrotik')], default=0)),
                ('last_backup', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', ndam.fields.EncryptedField(max_length=100)),
            ],
            options={
                'verbose_name': 'Device Credential',
                'verbose_name_plural': 'Device Credentials',
            },
        ),
        migrations.CreateModel(
            name='DeviceBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('data', models.FileField(upload_to='backups')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='ndam.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='ndam.devicecredential'),
        ),
    ]
