# Generated by Django 4.2.1 on 2023-05-28 07:52

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ndam', '0003_device_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_backup',
        ),
        migrations.AlterField(
            model_name='devicecredential',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_backup', models.DateTimeField(blank=True, editable=False, null=True)),
                ('state', models.IntegerField(choices=[(0, 'Success'), (1, 'Failed'), (2, 'In Progress')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='ndam.device')),
            ],
            options={
                'verbose_name': 'Device Status',
                'verbose_name_plural': 'Device Status',
                'ordering': ['-created_at'],
            },
        ),
    ]
